### PR TITLE
Update to fit lib.rs changes

### PR DESCRIPTION
**Pull request by pythcoiner**
- [x] ledger_service.rs::check_apps_installed() now use the 'new' list_installed_apps()
 - [x] remove get_app_version() as its not used anymore by check_apps_installed() 
 - [x] get the actual installed app version

### CODE REVIEW

**Comment by pythcoiner** [comment]
@darosior, about the genuine check feature, how do you see it? display a `Genuine check` button if no app installed?

**Comment by darosior** [comment]
> about the genuine check feature, how do you see it? display a `Genuine check` button if no app installed?

i'd rather have a clickable button to perform the genuine check.

**Comment by darosior** [comment]
Yes.

**Comment by darosior** [comment]
ACK, tested using a Nano S and a Nano S+.

**Pull request merged**
